sync

diff --git a/bin/rogems b/bin/rogems
--- a/bin/rogems
+++ b/bin/rogems
@@ -1,17 +1,13 @@
-#!/bin/env bash
+#!/bin/bash
 
 # Check if Ruby is installed
-if ! command -v ruby &> /dev/null
-then
-    echo "Error: Ruby is not installed or could not be located. Please install Ruby or add it to your PATH and try again."
+if ! command -v ruby &> /dev/null; then
+    echo "Error: Ruby is not installed. Please install Ruby and try again."
     exit 1
 fi
 
-# Run the RoGems.rb script
+# Get the script's current directory
 current_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-arg_string=""
-for arg in "$@"
-do
-  arg_string="$arg_string $arg"
-done
-ruby "$current_dir/../src/RoGems.rb" $arg_string
+
+# Run the RoGems.rb script
+ruby "$current_dir/../src/RoGems.rb" "$@"
